tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "itchyny/tap"
tap "nodenv/nodenv"
tap "yt-dlp/taps"
brew "anyenv"
brew "webp"
brew "readline"
brew "xz"
brew "bitwarden-cli"
brew "boost"
brew "freetype"
brew "pkg-config"
brew "tcl-tk"
brew "ccache"
brew "cmake"
brew "deno"
brew "direnv"
brew "docker-machine"
brew "unbound"
brew "mbedtls"
brew "ffmpeg"
brew "firebase-cli"
brew "fzy"
brew "gdk-pixbuf"
brew "gh"
brew "ghostscript"
brew "git"
brew "gnu-sed"
brew "gphoto2"
brew "jasper"
brew "netpbm"
brew "pango"
brew "graphviz"
brew "gtk+3"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "ldns"
brew "lilv"
brew "mas"
brew "mitmproxy"
brew "yt-dlp"
brew "mpv"
brew "node-build"
brew "openapi-generator"
brew "openssh"
brew "poppler"
brew "portaudio"
brew "qt"
brew "sox"
brew "suil"
brew "swig"
brew "the_silver_searcher"
brew "wget"
brew "ykman"
brew "youtube-dl"
brew "yubico-piv-tool"
brew "zplug"
brew "itchyny/tap/mmv"
brew "nodenv/nodenv/nodenv-package-json-engine"
brew "yt-dlp/taps/yt-dlp"
cask "amethyst"
cask "blackhole-2ch"
cask "docker"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "macfuse"
cask "openmtp"
cask "opensc"
cask "pgadmin4"
cask "vlc"
mas "CleanMyDrive 2", id: 523620159
mas "DevCleaner", id: 1388020431
mas "Duplicate Photos Finder", id: 984929789
mas "Flycut", id: 442160987
mas "Free Ruler", id: 1483172210
mas "GIPHY CAPTURE", id: 668208984
mas "Kindle", id: 405399194
mas "Medis", id: 1579200037
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Surfshark", id: 1437809329
mas "Timer RH", id: 929960914
mas "Xcode", id: 497799835
mas "Yubico Authenticator", id: 1497506650
