tap "aquaproj/aqua"
tap "felixkratz/formulae"
tap "yt-dlp/taps"
brew "actionlint"
brew "xz"
brew "webp"
brew "aqua"
brew "berglas"
brew "freetype"
brew "cloud-sql-proxy"
brew "readline"
brew "deno"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "docker-credential-helper"
brew "unbound"
brew "mbedtls"
brew "pango"
brew "tesseract"
brew "ffmpeg"
brew "fzf"
brew "gdk-pixbuf"
brew "gh"
brew "ghq"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "jasper"
brew "netpbm"
brew "graphviz"
brew "hurl"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "ldns"
brew "libyaml"
brew "lima"
brew "mas"
brew "mise"
brew "nkf"
brew "pkgconf"
brew "node-build"
brew "openssh"
brew "pdfcpu"
brew "pinact"
brew "tesseract-lang"
brew "tfenv"
brew "wget"
brew "yt-dlp"
brew "yubico-piv-tool"
brew "zplug"
brew "felixkratz/formulae/borders"
cask "amethyst"
cask "appcleaner"
cask "aqua-voice"
cask "arc"
cask "bitwarden"
cask "blackhole-2ch"
cask "figma"
cask "font-fira-code"
cask "gather"
cask "gcloud-cli"
cask "git-credential-manager"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "obsidian"
cask "openmtp"
cask "raycast"
cask "rocket"
cask "secretive"
cask "shottr"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
cask "zoom"
mas "DevCleaner", id: 1388020431
mas "Free Ruler", id: 1483172210
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Keeper Password Manager", id: 414781829
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
mas "Yubico Authenticator", id: 1497506650
